server:
  port: 8081

spring:
  application:
    name: external-microservices

routee:
  app-id: 5bba56ece4b0a43fbf239aae
  app-secret: kDsvtwHe3w
  sender: SFGo # δεν μπορω να γραψω ολοκληρο το StreetFoodGo :(

nominatim:
  url: "https://nominatim.openstreetmap.org/search"
  user-agent: "StreetFoodGo-Microservice/1.0 (it2022088@hua.gr)"

ors:
  api-key: eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjJlNTMxMWIzOWRmODRjMDZhYjc1ZmJlYzU2ZDRjNGUxIiwiaCI6Im11cm11cjY0In0=
  base-url: "https://api.openrouteservice.org/v2/directions/driving-car"